#import
builtin.colors.tailwind as tw

#defs
// GlobalZIndex
$ZINDEX_LOADSCREEN = 10

// Colors
$COLOR_LOADSCREEN = $tw::STONE_400
$COLOR_LOADBAR_GUTTER = $tw::ZINC_400
$COLOR_LOADBAR = $tw::ZINC_600
$COLOR_GAMEOVER = $tw::NEUTRAL_800
$COLOR_GAME_BG = $tw::SKY_800
$COLOR_GAME_CLICKER = $tw::LIME_600
$COLOR_GAME_SECONDARY_BUTTONS = $tw::AMBER_600
