[package]
name = "bevy_girk_click_demo_user_client_bin"
version.workspace = true
edition.workspace = true

[[bin]]
name    = "bevy_girk_click_demo_user_client_bin"
test    = false
doctest = false

[dependencies]
bevy = { workspace = true, features = [ "multi-threaded" ] }

bevy_girk_utils = { workspace = true }

bevy_girk_demo_user_client = { path = "../../libs/bevy_girk_demo_user_client" }
